// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bproject.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Fraction             string   `protobuf:"bytes,2,opt,name=fraction,proto3" json:"fraction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab5db2ada4e8cfc1, []int{0}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddUserRequest) GetFraction() string {
	if m != nil {
		return m.Fraction
	}
	return ""
}

type AddUserReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserReply) Reset()         { *m = AddUserReply{} }
func (m *AddUserReply) String() string { return proto.CompactTextString(m) }
func (*AddUserReply) ProtoMessage()    {}
func (*AddUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab5db2ada4e8cfc1, []int{1}
}

func (m *AddUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserReply.Unmarshal(m, b)
}
func (m *AddUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserReply.Marshal(b, m, deterministic)
}
func (m *AddUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserReply.Merge(m, src)
}
func (m *AddUserReply) XXX_Size() int {
	return xxx_messageInfo_AddUserReply.Size(m)
}
func (m *AddUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserReply proto.InternalMessageInfo

type GetUserRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab5db2ada4e8cfc1, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserReply struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Fraction             string   `protobuf:"bytes,2,opt,name=fraction,proto3" json:"fraction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReply) Reset()         { *m = GetUserReply{} }
func (m *GetUserReply) String() string { return proto.CompactTextString(m) }
func (*GetUserReply) ProtoMessage()    {}
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab5db2ada4e8cfc1, []int{3}
}

func (m *GetUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReply.Unmarshal(m, b)
}
func (m *GetUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReply.Marshal(b, m, deterministic)
}
func (m *GetUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReply.Merge(m, src)
}
func (m *GetUserReply) XXX_Size() int {
	return xxx_messageInfo_GetUserReply.Size(m)
}
func (m *GetUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReply proto.InternalMessageInfo

func (m *GetUserReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserReply) GetFraction() string {
	if m != nil {
		return m.Fraction
	}
	return ""
}

func init() {
	proto.RegisterType((*AddUserRequest)(nil), "pb.AddUserRequest")
	proto.RegisterType((*AddUserReply)(nil), "pb.AddUserReply")
	proto.RegisterType((*GetUserRequest)(nil), "pb.GetUserRequest")
	proto.RegisterType((*GetUserReply)(nil), "pb.GetUserReply")
}

func init() { proto.RegisterFile("bproject.proto", fileDescriptor_ab5db2ada4e8cfc1) }

var fileDescriptor_ab5db2ada4e8cfc1 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2a, 0x28, 0xca,
	0xcf, 0x4a, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xf2,
	0xe0, 0xe2, 0x73, 0x4c, 0x49, 0x09, 0x2d, 0x4e, 0x2d, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x92, 0xe2, 0xe2, 0x28, 0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x69, 0x45, 0x89, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0x12,
	0x4c, 0x10, 0x39, 0x18, 0x5f, 0x89, 0x8f, 0x8b, 0x07, 0x6e, 0x52, 0x41, 0x4e, 0xa5, 0x92, 0x06,
	0x17, 0x9f, 0x7b, 0x6a, 0x09, 0xb2, 0xc9, 0x62, 0x5c, 0x6c, 0x20, 0x93, 0x3c, 0x5d, 0xc0, 0xe6,
	0x32, 0x07, 0x41, 0x79, 0x4a, 0x6e, 0x5c, 0x3c, 0x70, 0x95, 0x05, 0x39, 0x95, 0xe4, 0xba, 0xc0,
	0x28, 0x87, 0x8b, 0xc3, 0x29, 0x00, 0xe2, 0x43, 0x21, 0x7d, 0x2e, 0x76, 0xa8, 0x6b, 0x84, 0x84,
	0xf4, 0x0a, 0x92, 0xf4, 0x50, 0x3d, 0x29, 0x25, 0x80, 0x22, 0x06, 0xb2, 0x54, 0x9f, 0x8b, 0x1d,
	0xea, 0x08, 0x88, 0x06, 0x54, 0xb7, 0x43, 0x34, 0x20, 0xbb, 0x32, 0x89, 0x0d, 0x1c, 0x88, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x51, 0xc6, 0xd5, 0x56, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BProjectClient is the client API for BProject service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BProjectClient interface {
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserReply, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error)
}

type bProjectClient struct {
	cc *grpc.ClientConn
}

func NewBProjectClient(cc *grpc.ClientConn) BProjectClient {
	return &bProjectClient{cc}
}

func (c *bProjectClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserReply, error) {
	out := new(AddUserReply)
	err := c.cc.Invoke(ctx, "/pb.BProject/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bProjectClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error) {
	out := new(GetUserReply)
	err := c.cc.Invoke(ctx, "/pb.BProject/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BProjectServer is the server API for BProject service.
type BProjectServer interface {
	AddUser(context.Context, *AddUserRequest) (*AddUserReply, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserReply, error)
}

// UnimplementedBProjectServer can be embedded to have forward compatible implementations.
type UnimplementedBProjectServer struct {
}

func (*UnimplementedBProjectServer) AddUser(ctx context.Context, req *AddUserRequest) (*AddUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedBProjectServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterBProjectServer(s *grpc.Server, srv BProjectServer) {
	s.RegisterService(&_BProject_serviceDesc, srv)
}

func _BProject_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BProjectServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BProject/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BProjectServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BProject_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BProjectServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BProject/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BProjectServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BProject_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BProject",
	HandlerType: (*BProjectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _BProject_AddUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _BProject_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bproject.proto",
}
