// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "bproject/pkg/endpoint"
	pb "bproject/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	addUser grpc.Handler
	getUser grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.BProjectServer {
	return &grpcServer{
		addUser: makeAddUserHandler(endpoints, options["AddUser"]),
		getUser: makeGetUserHandler(endpoints, options["GetUser"]),
	}
}
